services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      network: host
    container_name: laravel_app
    volumes:
      - project-html:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    # network_mode: host
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    # network_mode: host
    ports:
      - "8000:80"
    volumes:
      - project-html:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_db
    restart: unless-stopped
    # network_mode: host
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  project-html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./html
  dbdata:

networks:
  laravel:
    driver: bridge
